---
title: "JSC370 Final Project"
author: "Chloe Nguyen"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

<br>

Lab 12 visuals.

<br>

```{r setup, message=FALSE, echo=FALSE, warning=FALSE}

library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(knitr)

# Initialize code chunk options
opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = TRUE,
  cache = FALSE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px",
  class.source = "code-r",
  cache=TRUE)
```

```{css, echo = FALSE}
.code-r { /* Code block */
  font-size: 15px;
}

.code-r-small { /* Code block */
  font-size: 10px;
}
```

<br>

## Step 11: Source processing code

Source necessary code (`process_covid_data.R`):

```{r load-data}
source("process_COVID_data.R")
```

<br>

## Step 12: Add code for visuals

Using **plotly** for figures

```{r plot1, class.source="code-r-small"}

p1_scatter <- cv_states_today %>% 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")

# filter out "District of Columbia"
cv_states_today_scatter <- cv_states_today %>% filter(state!="District of Columbia")

p2_scatter <- cv_states_today_scatter %>% 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")
```

<br>

## Step 13: Display figures in tabs {.tabset}

Displaying figures with tabs

### Scatterplot: with DC

```{r p1}
p1_scatter
```

### Scatterplot: without DC

```{r p2}
p2_scatter
```

## My own plots {.tabset}

### Figure 1

```{r}

cv_states_mat <- cv_states %>%
  select(state, date, new_cases) %>%
  filter(date > "2021-07-01")

cv_states_mat2 <- as.data.frame(pivot_wider(cv_states_mat, names_from = state, values_from=new_cases))

cv_states_mat2 <- cv_states_mat2 %>%
  column_to_rownames("date") %>%
  as.matrix()

plot_ly(x=colnames(cv_states_mat2), y=rownames(cv_states_mat2), z=cv_states_mat2, type="heatmap")
```


### Figure 2

```{r}

cv_states %>%
  plot_ly(x=~date, y=~naive_CFR, color=~state, type="scatter", mode="lines")

```

## {-}

<br>

Done!

<br>
<br>